version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: books
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  cache:
    image: redis:7.0.5-alpine3.17
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass compage123
    volumes:
      - cache:/data
#  core:
#    build:
#      dockerfile: Dockerfile
#      context: "./core"
#    volumes:
#      - "./vendor:/vendor"
#    ports:
#      - "9906:3306"
#    environment:
#      <<: *common-variables
#      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
#      MYSQL_HOST: localhost
#
#  app:
#    build:
#      dockerfile: Dockerfile
#      context: "./app"
#    depends_on:
#      - core
#    volumes:
#      - /app/node_modules
#      - ./app:/app
#    environment:
#      <<: *common-variables
#      MYSQL_HOST_IP: mysql_db
#
#  ui:
#    stdin_open: true
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    build:
#      dockerfile: Dockerfile
#      context: ./ui
#    volumes:
#      - /app/node_modules
#      - ./ui:/app
#
#  nginx:
#    depends_on:
#      - app
#      - ui
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    ports:
#      - "3050:80"

volumes:
  cache:
    driver: local