{{- if eq .Values.app.db.type "cassandra" }}
apiVersion: v1
kind: Secret
metadata:
  name: db-cassandra-credentials
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
type: Opaque
stringData:
  CASSANDRA_CONTACT_POINTS: {{ .Values.app.db.cassandra.contactPoints }}
  CASSANDRA_LOCAL_DATA_CENTER: {{ .Values.app.db.cassandra.localDataCenter }}
  CASSANDRA_KEYSPACE: {{ .Values.app.db.cassandra.keyspace }}
  CASSANDRA_USERNAME: {{ .Values.app.db.cassandra.username }}
  CASSANDRA_PASSWORD: {{ .Values.app.db.cassandra.password }}
{{- end }}