apiVersion: v1
kind: Secret
metadata:
  name: app-github-credentials
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_APP_CLIENT_ID: {{ .Values.githubApp.clientId }}
  GITHUB_APP_CLIENT_SECRET: {{ .Values.githubApp.clientSecret }}