# github config
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-github
  namespace: compage
data:
  GITHUB_APP_REDIRECT_URI: "http://{{KIND_NODE_IP}}:32222/login"
---
# app-data config | core connection details
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-data
  namespace: compage
data:
  COMPAGE_CORE_URL: "core:50051"