---
# redis deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: redis
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.5-alpine3.17
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
              name: http
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis-data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
---
# redis configmap
apiVersion: v1
data:
  redis.conf: |
    #############################
    ## Default redis.conf file           ##
    #############################
    # allow access from all instances
    protected-mode no
    # limit memory usage, discard unused keys when hitting limit
    maxmemory 6gb
    maxmemory-policy allkeys-lru
    # snapshots on disk every minute
    dir /redis-data/
    appendonly no
    save 60 1

    ###################
    ## Customization ##
    ###################
    requirepass compage123

kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis

---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  labels:
    app: redis
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: http
      protocol: TCP
  selector:
    app: redis
