apiVersion: v1
kind: Secret
metadata:
  name: app-github-credentials
  namespace: compage
type: Opaque
data:
  GITHUB_APP_CLIENT_ID: NWY4YjgyMDhmZmEwMDAzMTZkMmQ=
  GITHUB_APP_CLIENT_SECRET: ZTk2NDNhMmI3MjI0MmUzYjE5YzQyYTM4N2ZhM2Y1YTAyMDVmMzY4YQ==