apiVersion: v1
kind: Service
metadata:
  namespace: compage
  labels:
    app: app
  name: app
spec:
  ports:
    - port: 5000
      nodePort: 31111
      targetPort: http
  selector:
    app: app
  type: NodePort