## Define serviceAccount names for components. Defaults to component's fully qualified name.
githubApp:
  redirectURI: "http://172.18.0.2:32222/login"
  clientId: "NWY4YjgyMDhmZmEwMDAzMTZkMmQ="
  clientSecret: "ZTk2NDNhMmI3MjI0MmUzYjE5YzQyYTM4N2ZhM2Y1YTAyMDVmMzY4YQ=="

app:
  enabled: true
  name: app
  replicaCount: 1
  serviceAccount:
    create: true
    name:
    annotations: {}
  image:
    repository: ghcr.io/mahendraintelops/compage/app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: "app"
  fullnameOverride: ""
  compageCoreURL: "core:50051"
  podAnnotations: {}

  podSecurityContext: {}

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534

  service:
    type: NodePort
    nodePort: 31111
    port: 5000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
core:
  enabled: true
  name: core
  replicaCount: 1
  serviceAccount:
    create: true
    name:
    annotations: {}
  image:
    repository: ghcr.io/mahendraintelops/compage/core
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: "core"
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534

  service:
    type: ClusterIP
    port: 50051

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
ui:
  enabled: true
  name: ui
  replicaCount: 1
  serviceAccount:
    create: true
    name:
    annotations: {}
  image:
    repository: ghcr.io/mahendraintelops/compage/ui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: "ui"
  fullnameOverride: ""
  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  compageApp:
    serverUrl: http://172.18.0.2:31111
  podAnnotations: {}

  podSecurityContext: {}

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534

  service:
    type: NodePort
    nodePort: 32222
    port: 3000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
