## Define serviceAccount names for components. Defaults to component's fully qualified name.
githubApp:
  # update below value cluster's node ip and with port specified here (.Values.ui.service.nodePort)
  redirectURI: "http://www.compage.dev:32222/login"
  clientId: "NWY4YjgyMDhmZmEwMDAzMTZkMmQ="
  clientSecret: "YmI0MTg5YmM5MjQ2MWY4YjZhM2UzNWZjMzFhYzFhMjVmYWUwMTE0Ngo="

# TODO the below is not yet configurable. Code has direct references so, any change in below value will break the application.
systemNamespace: compage

app:
  enabled: true
  name: app
  replicaCount: 1
  serviceAccount:
    create: true
    name:
    annotations: {}
  image:
    repository: ghcr.io/mahendraintelops/compage/app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets:
  - name: "compage-pull-secret"
  nameOverride: "app"
  fullnameOverride: ""
  podAnnotations: {}

  podSecurityContext: {}

#  securityContext:
#    runAsUser: 65534
#    runAsNonRoot: true
#    runAsGroup: 65534

  service:
    type: NodePort
    nodePort: 31111
    port: 5000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
core:
  enabled: true
  name: core
  replicaCount: 1
  serviceAccount:
    create: true
    name:
    annotations: {}
  image:
    repository: ghcr.io/mahendraintelops/compage/core
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets:
  - name: "compage-pull-secret"
  nameOverride: "core"
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534

  service:
    type: ClusterIP
    port: 50051

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
ui:
  enabled: true
  name: ui
  replicaCount: 1
  serviceAccount:
    create: true
    name:
    annotations: {}
  image:
    repository: ghcr.io/mahendraintelops/compage/ui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets:
  - name: "compage-pull-secret"
  nameOverride: "ui"
  fullnameOverride: ""
  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  compageApp:
#   update below value cluster's node ip and with port specified here (.Values.app.service.nodePort)
    serverUrl: http://www.compage.dev:31111
  podAnnotations: {}

  podSecurityContext: {}

#  securityContext:
#    runAsUser: 65534
#    runAsNonRoot: true
#    runAsGroup: 65534

  service:
    type: NodePort
    nodePort: 32222
    port: 80

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
