## Define serviceAccount names for components. Defaults to component's fully qualified name.
serviceAccounts:
  app:
    create: true
    name:
    annotations: {}
  core:
    create: true
    name:
    annotations: {}
  ui:
    create: true
    name:
    annotations: {}

app:
  enabled: true
  name: app
  replicaCount: 1

  image:
    repository: ghcr.io/mahendraintelops/compage/app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: "compage"

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
  
  service:
    type: NodePort
    port: 80

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
core:
  enabled: true
  name: app
  replicaCount: 1

  image:
    repository: ghcr.io/mahendraintelops/compage/core
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: "compage"

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534

  service:
    type: NodePort
    port: 80

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
ui:
  enabled: true
  name: app
  replicaCount: 1

  image:
    repository: ghcr.io/mahendraintelops/compage/ui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []
  nameOverride: "compage"

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534

  service:
    type: NodePort
    port: 80

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
