apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compage-crd-crud-rolebinding
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "compage.app.serviceAccountName" . }}
    namespace: {{ .Values.systemNamespace }}
roleRef:
  kind: Role
  name: compage-crd-crud-role
  apiGroup: rbac.authorization.k8s.io
