apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compage-ns-read-cluster-role-binding
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "compage.app.serviceAccountName" . }}
    namespace: {{ .Values.systemNamespace }}
roleRef:
  kind: ClusterRole
  name: compage-ns-read-cluster-role
  apiGroup: rbac.authorization.k8s.io