apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compage-crd-crud-role
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
rules:
  - apiGroups: ["compage.intelops.github.com"]
    resources: ["*"]
    verbs: ["*"]