apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compage-ns-read-cluster-role
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]