apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: compage
  name: core
  labels:
    app: core
spec:
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
        name: core
    spec:
      containers:
        - name: core
          image: ghcr.io/mahendraintelops/compage/core
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 15
            periodSeconds: 30
