apiVersion: v1
entries:
  compage:
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2023-04-30T22:25:53.329987882+05:30"
    description: A Helm chart for Kubernetes
    digest: 47b64ab6b43577575ad4dd2412b4744ceb93ad15c3b59b4e2c760547ad8d6689
    icon: https://raw.githubusercontent.com/intelops/compage/main/ui/public/compage-512x512.png
    name: compage
    type: application
    urls:
    - compage-v0.0.1.tgz
    version: v0.0.1
generated: "2023-04-30T22:25:53.328916101+05:30"
