apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compage.app.fullname" . }}
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "compage.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "compage.app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "compage.app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
          env:
            - name: SYSTEM_NAMESPACE
              value: Values.systemNamespace
            - name: COMPAGE_CORE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-data
                  key: COMPAGE_CORE_URL
            - name: GITHUB_APP_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: app-github
                  key: GITHUB_APP_REDIRECT_URI
          volumeMounts:
            - name: github-credentials
              mountPath: "/etc/github-credentials"
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: github-credentials
          secret:
            secretName: app-github-credentials
            defaultMode: 0400
            items:
              - key: GITHUB_APP_CLIENT_ID
                path: compage/GITHUB_APP_CLIENT_ID
              - key: GITHUB_APP_CLIENT_SECRET
                path: compage/GITHUB_APP_CLIENT_SECRET