{{- if .Values.core.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compage.core.serviceAccountName" . }}
  labels:
    {{- include "compage.core.labels" . | nindent 4 }}
  {{- with .Values.core.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
