apiVersion: v1
kind: ConfigMap
metadata:
  name: app-github
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
data:
  GITHUB_APP_REDIRECT_URI: {{.Values.githubApp.redirectURI}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-data
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
data:
  COMPAGE_CORE_URL: {{ include "compage.core.fullname" . }}:{{.Values.core.service.port}}