---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-data
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
data:
  COMPAGE_CORE_URL: {{ include "compage.core.fullname" . }}:{{.Values.core.service.port}}