apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: compage
  name: ui
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
        name: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/mahendraintelops/compage/ui:qYbaUtG
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: REACT_APP_GITHUB_APP_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: ui-data
                  key: REACT_APP_GITHUB_APP_REDIRECT_URI
            - name: REACT_APP_GITHUB_APP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: ui-data
                  key: REACT_APP_GITHUB_APP_CLIENT_ID
            - name: REACT_APP_COMPAGE_APP_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: ui-data
                  key: REACT_APP_COMPAGE_APP_SERVER_URL
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
