apiVersion: v1
kind: Service
metadata:
  namespace: compage
  labels:
    app: ui
  name: ui
spec:
  ports:
    - port: 3000
      nodePort: 32222
      name: http
  selector:
    app: ui
  type: NodePort
