apiVersion: v1
kind: Service
metadata:
  namespace: compage
  labels:
    app: ui
  name: ui
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      nodePort: 30102
  selector:
    app: ui
  type: NodePort
