apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: compage
  name: compage-app
  labels:
    app: compage-app
spec:
  selector:
    matchLabels:
      app: compage-app
  template:
    metadata:
      labels:
        app: compage-app
        name: compage-app
    spec:
      containers:
        - name: compage-app
          image: mahendraintelops/compage-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: COMPAGE_CORE_URL
              value: "localhost:50051"
          volumeMounts:
            - name: github
              mountPath: "/etc/github"
              readOnly: true
            - name: redis
              mountPath: "/etc/redis"
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: github
          secret:
            secretName: github-config
            defaultMode: 0400
        - name: redis
          secret:
            secretName: redis-config
            defaultMode: 0400
