apiVersion: v1
kind: Secret
metadata:
  name: github-config
  namespace: compage
type: Opaque
data:
  GITHUB_APP_CLIENT_ID: 5f8b8208ffa000316d2d
  GITHUB_APP_CLIENT_SECRET: e9643a2b72242e3b19c42a387fa3f5a0205f368a
  GITHUB_APP_REDIRECT_URI: http://localhost:3000/login

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-config
  namespace: compage
type: Opaque
data:
  REDIS_HOST: 192.168.1.29
  REDIS_PORT: 6379
  REDIS_PASSWORD: compage123
  REDIS_USERNAME: default