apiVersion: v1
kind: Service
metadata:
  name: {{ include "compage.app.fullname" . }}
  labels:
    {{- include "compage.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      nodePort: {{ .Values.app.service.nodePort }}
      targetPort: http
  selector:
    {{- include "compage.app.selectorLabels" . | nindent 4 }}
