apiVersion: v1
kind: Service
metadata:
  name: {{ include "compage.ui.fullname" . }}
  labels:
    {{- include "compage.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      nodePort: {{ .Values.ui.service.nodePort }}
      targetPort: http
  selector:
    {{- include "compage.ui.selectorLabels" . | nindent 4 }}
